# Generated by Django 4.0.5 on 2022-06-13 09:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Superhero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.datetime(2022, 6, 13, 9, 52, 51, 361800, tzinfo=utc))),
                ('createur', models.CharField(max_length=100)),
                ('acteurs', models.TextField()),
                ('super_pouvoir', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_film', models.CharField(max_length=100)),
                ('producteur', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.datetime(2022, 6, 13, 9, 52, 51, 599143, tzinfo=utc))),
                ('resume', models.TextField()),
                ('superhero', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='Films_MCU.superhero')),
            ],
        ),
    ]
