# Generated by Django 4.0.3 on 2022-06-15 11:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoriesfilms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=45, null=True)),
                ('descriptif', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'CategoriesFilms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Superhero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.datetime(2022, 6, 15, 11, 24, 30, 74105, tzinfo=utc))),
                ('createur', models.CharField(max_length=100)),
                ('acteurs', models.TextField()),
                ('super_pouvoir', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_film', models.CharField(max_length=100)),
                ('producteur', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.datetime(2022, 6, 15, 11, 24, 30, 106761, tzinfo=utc))),
                ('resume', models.TextField()),
                ('superhero', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='Films_MCU.superhero')),
            ],
        ),
    ]
