# Generated by Django 4.0.3 on 2022-06-16 06:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Films_MCU', '0003_alter_films_date_alter_superhero_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 16, 6, 47, 58, 640737, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 16, 6, 47, 58, 613305, tzinfo=utc)),
        ),
    ]
