# Generated by Django 4.0.3 on 2022-06-17 10:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Films_MCU', '0006_alter_films_date_alter_superhero_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 17, 10, 47, 13, 918553, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 17, 10, 47, 13, 889090, tzinfo=utc)),
        ),
    ]
